@apimEndpoint = apim-dev-we-rds-17d3.azure-api.net/products
@products = people
@typeJson = Accept: application/json

###
# @name = Get Products from APIM Endpoint
GET https://{{apimEndpoint}}/{{products}}
{{typeJson}}
