@apimEndpoint = <YOUR-APIM-RESOURCE-NAME>.azure-api.net
@products = products
@typeJson = Accept: application/json

###
# @name = Get Products from APIM Endpoint
GET https://{{apimEndpoint}}/{{products}}
{{typeJson}}
