name: Update workshop packages
on:
  push:
    branches:
      - main

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: cache-refresh-func zip
      run:  cd src/cache-refresh-func && zip -r ../../cache-refresh-func.zip .

    - name: history-func zip
      run:  cd src/history-func && zip -r ../../history-func.zip .

    - name: API zip
      run:  cd src/catalog-api && zip -r ../../catalog-api.zip .

    - name: APIM Policies zip
      run:  cd src/apim-policies && zip -r ../../apim-policies.zip .

    - name: Database sample data zip
      run:  cd src/seed && zip -r ../../database-sample-data.zip .

    - name: Infrastructure As Code zip
      run:  cd terraform && zip -r ../terraform.zip .

    - name: Update release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Workshop packages
        tag: latest
        artifacts: "*.zip"
        allowUpdates: true